### ISSUE TITLE
Properly handling trailing newline

### ISSUE THREAD

**Issue by isti115** [AndrasKovacs/sett#1]
Extending the second branch of `topLevel` as we've discussed (`ws >> eof`) was not enough, as the parser eagerly commits to parsing a top-level definition as soon as it gets to the ending newline with zero indentation.

I have added a workaround in e7395d997b509b0a66401f2c44054bb13c77ea91 by extending the indentation check with a condition that ensures that the file does not end immediately after the newline character, but there is probably a cleaner solution.

**Comment by szumixie** [comment]
I added a slightly cleaner solution in 128f50f0070118571a056e3c022fd64e302f45a0.
